{% set name = "picows" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/picows-{{ version }}.tar.gz
  sha256: 0c388edf2aa42ec5fbf1cb53834a70ad071c8f0af7a8c3235c597549a013607e

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=61.0
    - wheel
    - cython >=3.0
    - pip
  run:
    - python
    - multidict

test:
  imports:
    - picows
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tarasko/picows
  doc_url: https://picows.readthedocs.io/en/stable/
  summary: Fast websocket client and server for asyncio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
