schema_version: 1

context:
  name: picows
  version: "1.13.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/picows-${{ version }}.tar.gz
  sha256: 58373438580e6fc8d88260382404b6c3cf58af4d9f33a09fd84cc6967d325476

build:
  skip: match(python, "<3.11")
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
  host:
    - python
    - setuptools >=78.0
    - wheel
    - cython >=3.0
    - pip
  run:
    - python
    - multidict
    - python-socks

tests:
  - python:
      imports:
        - picows
      pip_check: true

about:
  summary: Fast websocket client and server for asyncio
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tarasko/picows
  documentation: https://picows.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - thewchan
