schema_version: 1

context:
  name: picows
  version: "1.11.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/picows-${{ version }}.tar.gz
  sha256: b874327efd59e958290063d13dfdb499d756a7fb96af14e6fd7cdfcce818da76

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
  host:
    - python
    - setuptools >=78.0
    - wheel
    - cython >=3.0
    - pip
  run:
    - python
    - multidict

tests:
  - python:
      imports:
        - picows
      pip_check: true

about:
  summary: Fast websocket client and server for asyncio
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tarasko/picows
  documentation: https://picows.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - thewchan
